alter session set "_oracle_script"=true;
CREATE USER NAME_USER IDENTIFIED BY NAME_USER;
GRANT DBA TO NAME_USER;

--Criando tablespaces
--CREATE TABLESPACE IR_COMPARE_DATA DATAFILE 'C:\app\product\18.0.0\oradata\XE\TBS_DATA.DBF' SIZE 50M AUTOEXTEND ON; -- se necessário criar tablespace (DATA)
--CREATE TABLESPACE IR_COMPARE_INDEX DATAFILE 'C:\app\product\18.0.0\oradata\XE\TBS_INDEX.DBF' SIZE 50M AUTOEXTEND ON; --se necessário criar tablespace (INDEX)

--acesso aos tablespaces
--ALTER USER NAME_USER QUOTA UNLIMITED ON TABLESPACE_DATA; 
--ALTER USER NAME_USER QUOTA UNLIMITED ON TABLESPACE_INDEX;

GRANT EXECUTE ON DBMS_CRYPTO TO NAME_USER;
ALTER USER NAME_USER DEFAULT TABLESPACE TABLESPACE_DATA;

