DELETE FROM TABLE_NAME
WHERE ROWID IN(
    SELECT MIN(CC_.ROWID) FROM (
        SELECT COUNT(1) QTDE, CC.COLUMN_1, CC.COLUMN_2
        FROM TABLE_NAME CC
        WHERE CC.COLUMN_1 = 1
        GROUP BY CC.COLUMN_1, CC.COLUMN_2
    ) QRY
    INNER JOIN TABLE_NAME CC_
        ON CC_.COLUMN_1 = QRY.COLUMN_1
        AND CC_.COLUMN_2 = QRY.COLUMN_2
    WHERE QRY.QTDE > 1
    GROUP BY QRY.COLUMN_1, QRY.COLUMN_2
);