DECLARE
    COLUMN_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT (COLUMN_EXISTS , -01430);
    INDEX_JA_EXISTE EXCEPTION;
    PRAGMA EXCEPTION_INIT(INDEX_JA_EXISTE, -955);
    INDEX_NOT_EXISTS EXCEPTION;
    PRAGMA EXCEPTION_INIT (INDEX_NOT_EXISTS, -1418);
BEGIN
  BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE TPR_PAIS ADD CONTINENTE VARCHAR2(50)';
      EXCEPTION WHEN COLUMN_EXISTS THEN NULL;
    WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE ('Erro ao adicionar coluna CONTINENTE na tabela TPR_PAIS. ['||SQLERRM||']');
  END;
   
  BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX TMP_TAREFA_EXEC_MSG_1 ON TMP_TAREFA_EXEC_MSG (SEQUENCIA_INT)';
    EXCEPTION WHEN INDEX_JA_EXISTE THEN NULL;
  WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE ('Erro ao criar index TMP_TAREFA_EXEC_MSG_1. ['||SQLERRM||']');
  END;
   
  BEGIN
    EXECUTE IMMEDIATE 'DROP INDEX INT_DOC_SAIDA_IT_1';
    EXCEPTION WHEN INDEX_NOT_EXISTS THEN NULL;
  WHEN OTHERS THEN DBMS_OUTPUT.PUT_LINE ('Erro ao excluir index INT_DOC_SAIDA_IT_1. ['||SQLERRM||']');
  END;
 
END;
/
 
-- outra opção
BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE TPR_DIPJ_PARAM ADD LOG_IGNORAR_COD_PRODUTO NUMBER DEFAULT 0 NOT NULL';
  EXCEPTION WHEN OTHERS THEN
    IF SQLCODE=-01430 THEN NULL;
    ELSE dbms_output.put_line ('Erro ao adicionar coluna LOG_IGNORAR_COD_PRODUTO na tabela TPR_DIPJ_PARAM. ['||SQLERRM||']');
    END IF;
END;